apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-deployment-1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-1
  template:
    metadata:
      labels:
        app: container-1
    spec:
      containers:
        - name: container-1
          image: us-central1-docker.pkg.dev/cloud-computing-428914/kubernetes-artifact-repo/container-1-image
          imagePullPolicy: Always
          ports:
            - containerPort: 6000
          volumeMounts:
            - name: container-1-volume
              mountPath: /keval_PV_dir
      volumes:
        - name: container-1-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container-1-service
spec:
  selector:
    app: container-1
  ports:
    - protocol: TCP
      port: 80
      targetPort: 6000
  type: LoadBalancer