steps:
  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "build",
        "-t",
        "us-central1-docker.pkg.dev/cloud-computing-428914/kubernetes-artifact-repo/container-2-image:$COMMIT_SHA",
        ".",
      ]
    id: "Build image"

  - name: "gcr.io/cloud-builders/docker"
    args:
      [
        "push",
        "us-central1-docker.pkg.dev/cloud-computing-428914/kubernetes-artifact-repo/container-2-image:$COMMIT_SHA",
      ]
    id: "Push image"

  - name: "gcr.io/cloud-builders/kubectl"
    args: ["apply", "-f", "pvc.yaml"]
    id: "Create PV and PVC"
    env:
      - "CLOUDSDK_COMPUTE_REGION=us-central1"
      - "CLOUDSDK_COMPUTE_ZONE=us-central1-c"
      - "CLOUDSDK_CONTAINER_CLUSTER=gke-cluster"

  - name: "gcr.io/cloud-builders/gke-deploy"
    args:
      [
        "run",
        "--filename=deployment-2.yaml",
        "--location=us-central1",
        "--image=us-central1-docker.pkg.dev/cloud-computing-428914/kubernetes-artifact-repo/container-2-image:$COMMIT_SHA",
        "--cluster=gke-cluster",
      ]
    id: "Deploy app"

images:
  - "us-central1-docker.pkg.dev/cloud-computing-428914/kubernetes-artifact-repo/container-2-image:$COMMIT_SHA"

options:
  logging: CLOUD_LOGGING_ONLY
