apiVersion: apps/v1
kind: Deployment
metadata:
  name: container-deployment-2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: container-2
  template:
    metadata:
      labels:
        app: container-2
    spec:
      containers:
        - name: container-2
          image: us-central1-docker.pkg.dev/cloud-computing-428914/kubernetes-artifact-repo/container-2-image
          imagePullPolicy: Always
          ports:
            - containerPort: 6001
          volumeMounts:
            - name: container-2-volume
              mountPath: /keval_PV_dir
      volumes:
        - name: container-2-volume
          persistentVolumeClaim:
            claimName: host-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: container-2-service
spec:
  selector:
    app: container-2
  ports:
    - protocol: TCP
      port: 6001
      targetPort: 6001